spring:
  flyway:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE:LinguagemDB}?createDatabaseIfNotExist=true
    user: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWD:root}
    schemas:
      - ${DATABASE:LinguagemDB}
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE:LinguagemDB}?createDatabaseIfNotExist=true
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWD:root}
  jpa:
    hibernate:
      ddl:
        auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  profiles:
    active: dev
    jpa:
      hibernate:
        ddl-auto: update
    jackson:
      default-property-inclusion: non_ null